"""initial schema

Revision ID: 04629ceccf64
Revises: 
Create Date: 2026-05-11 00:10:11.331584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04629ceccf64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('airline_code', sa.String(length=3), nullable=False),
    sa.Column('flight_number', sa.String(length=16), nullable=False),
    sa.Column('origin_iata', sa.String(length=3), nullable=False),
    sa.Column('destination_iata', sa.String(length=3), nullable=False),
    sa.Column('scheduled_departure_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_arrival_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_departure_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aircraft_tail', sa.String(length=16), nullable=True),
    sa.Column('aircraft_type', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=24), server_default='scheduled', nullable=False, comment='scheduled, boarded, departed, arrived, diverted, cancelled, delayed'),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_airline_code'), 'flights', ['airline_code'], unique=False)
    op.create_table('policy_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doc_code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('section_ref', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_documents_doc_code'), 'policy_documents', ['doc_code'], unique=True)
    op.create_table('delay_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('flight_id', sa.String(length=36), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('reason_category', sa.String(length=32), nullable=False, comment='e.g. weather, atc, crew, maintenance, operational, airline, other'),
    sa.Column('reason_detail', sa.String(length=500), nullable=True),
    sa.Column('ata_chapter_hint', sa.String(length=80), nullable=True),
    sa.Column('recorded_at_utc', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('recorded_by_system', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delay_events_flight_id'), 'delay_events', ['flight_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delay_events_flight_id'), table_name='delay_events')
    op.drop_table('delay_events')
    op.drop_index(op.f('ix_policy_documents_doc_code'), table_name='policy_documents')
    op.drop_table('policy_documents')
    op.drop_index(op.f('ix_flights_airline_code'), table_name='flights')
    op.drop_table('flights')
    # ### end Alembic commands ###
